name: skuu
description: 千千AI

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#  intl: ^0.20.0
  flutter_screenutil: ^5.9.0
#  cupertino_icons: ^1.0.2
  dropdown_search: ^6.0.1
  auto_size_text: ^3.0.0
  adaptive_dialog: ^2.4.0
  flutter_staggered_grid_view: ^0.7.0
#  dash_chat: ^1.1.16
  image_network: ^2.5.1
  url_launcher: ^6.1.8
  infinite_carousel: ^1.1.1
  lpinyin: ^2.0.3
  scrollable_positioned_list: ^0.3.5
  comment_tree: ^0.3.0
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.0.0+1
  circular_menu: ^4.0.0
  flutter_json_view: ^1.1.4
  google_fonts: ^6.2.1
  #黄历
  lunar: ^1.6.1
  #日历视图
  calendar_date_picker2: ^1.1.7
  flutter_datetime_picker_plus: ^2.1.0
  table_calendar: ^3.1.3
  dio: ^5.4.0
  extended_nested_scroll_view: ^6.2.1
  easy_refresh: ^3.3.4
  flick_video_player:
    git:
      url: https://github.com/daicx/flick-video-player.git
  video_player: ^2.10.0
  # 基础的点击
  tapped: ^2.0.0
  # map取值
  safemap: ^2.1.0
  # 加载动画库
  flutter_spinkit: ^5.2.1
  provider: ^6.0.1
  visibility_detector: ^0.4.0+2
  spring: ^2.0.2
  easy_sidemenu: ^0.6.1
  file_selector: ^1.0.3
  awesome_dialog: ^3.2.0
  google_generative_ai: ^0.4.6
  cross_cache: 1.0.4
  flutter_chat_ui: ^2.9.0
  flutter_chat_core: ^2.8.0
  flyer_chat_audio_message: ^0.0.12+2
  flyer_chat_custom_message: ^0.0.12+3
  flyer_chat_file_message: ^2.3.1
  flyer_chat_image_message: ^2.2.1
  flyer_chat_location_message: 0.0.12+2
  flutter_link_previewer: ^4.1.2
  flyer_chat_text_message: ^2.5.1
  flyer_chat_system_message: ^2.1.13
  flyer_chat_text_stream_message: ^2.2.6
  flyer_chat_video_message: ^0.0.12+2
  pull_down_button: ^0.10.2
  web_socket_channel: ^3.0.3
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  http: '>=0.13.6 <2.0.0'
  flutter_chat_types: ^3.6.2
  mime: ^2.0.0
  open_filex: ^4.3.2
  path_provider: ^2.0.15
  qr_flutter: ^4.1.0
  chinese_font_library: ^1.2.0
  get: ^4.7.2
  logger: ^2.3.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.3
  get_thumbnail_video: ^0.7.3
  image_picker: ^1.1.2
  image: ^4.1.3
  geolocator: ^14.0.0
  flutter_weather_bg_null_safety: ^1.0.0
  city_pickers: ^1.3.0
  js: ^0.6.7
  qiniu_flutter_sdk: ^0.7.2
  file_picker: ^8.0.0+1
  flutter_widget_from_html: ^0.16.0
  carousel_slider: ^5.1.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_webrtc: ^0.9.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
#  fonts:
    #设置字体后，反而变慢了
#    - family: Noto
#      fonts:
#        - asset: fonts/NotoSansSC-Bold.otf
#        - asset: fonts/NotoSansSC-Medium.otf
#        - asset: fonts/NotoSansSC-Regular.otf
#          style: normal
  assets:
    - mock/
    - imgs/
    - imgs/weather/

#此处会导致无法为macos生成podfile
#  plugin:
#    platforms:
#      android:
#        package: com.shinow.qrscan
#        pluginClass: QrscanPlugin